version: '2'
services:
  student-app:
    image: student
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://student-postgresql:5432/Student
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://student-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://student-elasticsearch:9200
  student-postgresql:
    extends:
      file: postgresql.yml
      service: student-postgresql
  student-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: student-elasticsearch
